---
  - name: make a backup copy of the mirror.list configuration file
    ansible.builtin.file:
      src: '/etc/apt/mirror.list'
      dest: '/etc/apt/mirror.list.org'
      state: hard
      remote_src: true
    ignore_errors: yes
    tags: mirror_list_update

  - name: Distribution major version
    debug: 
      msg: "{{ ansible_distribution_major_version }}"
    tags: mirror_list_update

  - name: change the base_path to the default document root
    ansible.builtin.template:
      src: 'mirror.list.18.j2'
      dest: '/etc/apt/mirror.list'
      owner: 'root'
      group: 'root'
      mode: '0644'
      backup: yes
    when: ansible_distribution_major_version == '18'
    tags: mirror_list_update

  - name: change the base_path to the default document root
    ansible.builtin.template:
      src: 'mirror.list.2x.j2'
      dest: '/etc/apt/mirror.list'
      owner: 'root'
      group: 'root'
      mode: '0644'
      backup: yes
    when: ansible_distribution_major_version != '18'
    tags: mirror_list_update

  - name: collect all packages to their version
    ansible.builtin.shell: |
            dpkg -l | awk '{print $2 "," $3}' | sed -e '1,3d' | sed -e '2d' > /tmp/pkg_list.csv
    tags: pkg_version_collect

  - name: create a white list file
    ansible.builtin.template:
      src: 'white_list.j2'
      dest: '/tmp/white_list.csv'
      owner: 'root'
      group: 'root'
      mode: '0644'
      backup: yes
    tags: white_list_create

  - name: Compare package version between white list and pkg list
    ansible.builtin.shell: |
            grep -vf /tmp/pkg_list.csv /tmp/white_list.csv > /tmp/unmatch_list.csv
    tags: pkg_compare

  - name: disable automatic updates
    ansible.builtin.replace:
      path: '/etc/apt/apt.conf.d/20auto-upgrades'
      regexp: APT::Periodic::Update-Package-Lists "1";
      replace: APT::Periodic::Update-Package-Lists "0";
      backup: yes
    tags: disable_auto_updates

